apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeserver.common.names.name" $ | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "homeserver.app.labels.standard" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .port | default .containerPort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector: {{- include "homeserver.app.labels.matchLabels" $ | nindent 4 }}
